### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by velkyel** [bakpakin/dst#12]
Provide line numbers (in parser at least) and stack traces on errors please.

**Comment by bakpakin** [comment]
The parser code can currently collect byte offsets, from which line numbers can be computed. Most of the change should be modifying the run-context function which is implemented in src/compile/boot.dst. I definitely would like to add proper source mapping to the run-context function but have been intending to add byte offsets rather than line numbers to the reporting first.

TLDR; will probably add character index instead of line numbers first.

**Comment by bakpakin** [comment]
Hi there,

I have been working on the source mapping for a while, but really got it down in the last few days. 
Pull latest from master and see what you think - the source mapping should work during compilation, parsing, and for catching runtime errors.

**Comment by velkyel** [comment]
great, thank you.
